export const translations = {
  en: {
    appName: "InkFlow",
    dashboard: "Dashboard",
    myNovels: "My Novels",
    statistics: "Statistics",
    settings: "Settings",
    newNovel: "New Novel",
    welcomeBack: "Welcome back, Creator",
    dashboardSub: "Here's what's happening with your stories today.",
    totalTokens: "Total Tokens Used",
    totalViews: "Total Views",
    activeNovels: "Active Novels",
    tokenConsumption: "Token Consumption (Last 7 Days)",
    recentNovels: "Recent Novels",
    chapters: "Chapters",
    tokens: "Tokens",
    manageEmpire: "Manage your literary empire.",
    progress: "Progress",
    views: "Views",
    editingChapter: "Editing Chapter",
    selectChapter: "Select a chapter",
    save: "Save",
    publish: "Publish",
    addChapter: "Add Chapter",
    aiAssist: "AI Assist",
    aiWriting: "AI is writing...",
    novelOutline: "Novel Outline",
    outlinePlaceholder: "Define your world, characters, and plot...",
    analytics: "Analytics",
    analyticsSub: "Deep dive into your token usage and performance.",
    tokenUsageByNovel: "Token Usage by Novel",
    consumptionDistribution: "Consumption Distribution",
    tokenHistoryLog: "Token History Log",
    novel: "Novel",
    date: "Date",
    status: "Status",
    active: "Active",
    enterTitle: "Enter novel title:",
    newNovelDraft: "New novel draft",
    characters: "characters",
    words: "words",
    autoSaved: "Auto-saved",
    language: "Language",
    english: "English",
    chinese: "Chinese (Simplified)",
    startWriting: "Start writing your masterpiece...",
    selectToStart: "Select a chapter to start writing",
    fromLastWeek: "from last week",
    outlineVersions: "Outline Versions",
    activeVersion: "Active",
    newVersion: "New Version",
    activate: "Activate",
    versionName: "Version Name",
    outlineContext: "Active Outline Context",
    deleteNovel: "Delete Novel",
    confirmDelete: "Are you sure you want to delete this novel? This action cannot be undone.",
    generateOutline: "AI Generate Outline",
    generatingOutline: "Generating Outline...",
    batchGenerate: "Batch Generate",
    previewNovel: "Preview Novel",
    generateCount: "Number of chapters:",
    generatingChapters: "Generating chapters...",
    close: "Close",
    tableOfContents: "Table of Contents",
    aiSettings: "AI Settings",
    aiProvider: "AI Provider",
    aiModel: "AI Model",
    apiKey: "API Key",
    baseUrl: "Base URL (Optional)",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved successfully",
    gemini: "Google Gemini",
    openai: "OpenAI ChatGPT",
    deepseek: "DeepSeek",
    modelPlaceholder: "e.g., gpt-4o, deepseek-chat",
    apiKeyPlaceholder: "Enter your API key",
    custom: "Custom (OpenAI Compatible)",
    activeAI: "Active AI",
    writingConfig: "Writing Configuration",
    segmentedWrite: "Segmented Write",
    segmentedWriting: "Writing Segment...",
    wordCountRange: "Word Count Range",
    contentLayout: "Content Layout",
    layoutStandard: "Standard (Paragraphs)",
    layoutWeb: "Web Novel (Short Paragraphs)",
    layoutTraditional: "Traditional (Indented)",
    layoutPreview: "Layout Preview",
    minWords: "Min Words",
    maxWords: "Max Words"
  },
  zh: {
    appName: "墨流 (InkFlow)",
    dashboard: "控制面板",
    myNovels: "我的小说",
    statistics: "数据统计",
    settings: "设置",
    newNovel: "新建小说",
    welcomeBack: "欢迎回来，创作者",
    dashboardSub: "这是您今日的故事动态。",
    totalTokens: "总 Token 使用量",
    totalViews: "总浏览量",
    activeNovels: "活跃小说",
    tokenConsumption: "Token 消耗 (最近7天)",
    recentNovels: "最近小说",
    chapters: "章节",
    tokens: "Token",
    manageEmpire: "管理您的文学帝国。",
    progress: "进度",
    views: "浏览",
    editingChapter: "正在编辑章节",
    selectChapter: "请选择章节",
    save: "保存",
    publish: "发布",
    addChapter: "添加章节",
    aiAssist: "AI 辅助",
    aiWriting: "AI 正在创作...",
    novelOutline: "小说大纲",
    outlinePlaceholder: "定义您的世界、角色和情节...",
    analytics: "数据分析",
    analyticsSub: "深入了解您的 Token 使用情况和表现。",
    tokenUsageByNovel: "各小说 Token 使用量",
    consumptionDistribution: "消耗分布",
    tokenHistoryLog: "Token 历史记录",
    novel: "小说",
    date: "日期",
    status: "状态",
    active: "活跃",
    enterTitle: "输入小说标题：",
    newNovelDraft: "新小说草稿",
    characters: "字符",
    words: "单词",
    autoSaved: "已自动保存",
    language: "语言",
    english: "英文",
    chinese: "中文简体",
    startWriting: "开始创作您的杰作...",
    selectToStart: "选择一个章节开始写作",
    fromLastWeek: "较上周",
    outlineVersions: "大纲版本",
    activeVersion: "当前使用",
    newVersion: "新建版本",
    activate: "设为当前",
    versionName: "版本名称",
    outlineContext: "当前大纲上下文",
    deleteNovel: "删除小说",
    confirmDelete: "您确定要删除这部小说吗？此操作无法撤销。",
    generateOutline: "AI 生成大纲",
    generatingOutline: "正在生成大纲...",
    batchGenerate: "一键生成章节",
    previewNovel: "预览小说",
    generateCount: "生成章节数量：",
    generatingChapters: "正在批量生成章节...",
    close: "关闭",
    tableOfContents: "章节目录",
    aiSettings: "AI 设置",
    aiProvider: "AI 供应商",
    aiModel: "AI 模型",
    apiKey: "API 密钥",
    baseUrl: "基础 URL (可选)",
    saveSettings: "保存设置",
    settingsSaved: "设置已成功保存",
    gemini: "Google Gemini",
    openai: "OpenAI ChatGPT",
    deepseek: "DeepSeek",
    modelPlaceholder: "例如：gpt-4o, deepseek-chat",
    apiKeyPlaceholder: "输入您的 API 密钥",
    custom: "自定义 (兼容 OpenAI)",
    activeAI: "当前 AI",
    writingConfig: "创作配置",
    segmentedWrite: "分段创作",
    segmentedWriting: "正在分段创作...",
    wordCountRange: "字数范围",
    contentLayout: "内容排版",
    layoutStandard: "标准 (普通段落)",
    layoutWeb: "网文 (短段落/留白)",
    layoutTraditional: "传统 (首行缩进)",
    layoutPreview: "排版预览",
    minWords: "最小字数",
    maxWords: "最大字数"
  }
};

export type Language = 'en' | 'zh';
