export const translations = {
  en: {
    confirmReset: "Are you sure you want to reset all settings? This will clear your AI and writing configurations.",
    resetSettings: "Reset All Settings",
    previewOutline: "Preview Outline",
    editOutline: "Edit Outline",
    appName: "InkFlow",
    prevPage: "Previous",
    nextPage: "Next",
    page: "Page",
    of: "of",
    total: "Total",
    dashboard: "Dashboard",
    myNovels: "My Novels",
    statistics: "Statistics",
    settings: "Settings",
    newNovel: "New Novel",
    welcomeBack: "Welcome back, Creator",
    dashboardSub: "Here's what's happening with your stories today.",
    totalTokens: "Total Tokens Used",
    totalViews: "Total Views",
    activeNovels: "Active Novels",
    tokenConsumption: "Token Consumption (Last 7 Days)",
    recentNovels: "Recent Novels",
    chapters: "Chapters",
    tokens: "Tokens",
    manageEmpire: "Manage your literary empire.",
    progress: "Progress",
    views: "Views",
    editingChapter: "Editing Chapter",
    selectChapter: "Select a chapter",
    save: "Save",
    addChapter: "Add Chapter",
    aiAssist: "AI Assist",
    aiWriting: "AI is writing...",
    novelOutline: "Novel Outline",
    outlinePlaceholder: "Define your world, characters, and plot...",
    analytics: "Analytics",
    analyticsSub: "Deep dive into your token usage and performance.",
    tokenUsageByNovel: "Token Usage by Novel",
    consumptionDistribution: "Consumption Distribution",
    tokenHistoryLog: "Token History Log",
    novel: "Novel",
    date: "Date",
    status: "Status",
    active: "Active",
    enterTitle: "Enter novel title:",
    newNovelDraft: "New novel draft",
    characters: "characters",
    words: "words",
    autoSaved: "Auto-saved",
    language: "Language",
    english: "English",
    chinese: "Chinese (Simplified)",
    startWriting: "Start writing your masterpiece...",
    selectToStart: "Select a chapter to start writing",
    fromLastWeek: "from last week",
    clear: "Clear",
    outlineVersions: "Outline Versions",
    activeVersion: "Active",
    newVersion: "New Version",
    activate: "Activate",
    versionName: "Version Name",
    outlineContext: "Active Outline Context",
    deleteNovel: "Delete Novel",
    delete: "Delete",
    confirmDelete: "Are you sure you want to delete this novel? This action cannot be undone.",
    generateOutline: "AI Generate Outline",
    generatingOutline: "Generating Outline...",
    batchGenerate: "Batch Generate",
    previewNovel: "Preview Novel",
    generateCount: "Number of chapters:",
    generatingChapters: "Generating chapters...",
    close: "Close",
    cancel: "Cancel",
    novelStatus: "Novel Status",
    novelDraft: "In Progress",
    novelCompleted: "Completed",
    tableOfContents: "Table of Contents",
    aiSettings: "AI Settings",
    aiProvider: "AI Provider",
    aiModel: "AI Model",
    apiKey: "API Key",
    baseUrl: "Base URL (Optional)",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved successfully",
    gemini: "Google Gemini",
    openai: "OpenAI ChatGPT",
    deepseek: "DeepSeek",
    modelPlaceholder: "e.g., gpt-4o, deepseek-chat",
    apiKeyPlaceholder: "Enter your API key",
    custom: "Custom (OpenAI Compatible)",
    activeAI: "Active AI",
    writingConfig: "Writing Configuration",
    segmentedWrite: "Segmented Write",
    segmentedWriting: "Writing Segment...",
    wordCountRange: "Word Count Range",
    contentLayout: "Content Layout",
    layoutStandard: "Standard (Paragraphs)",
    layoutWeb: "Web Novel (Short Paragraphs)",
    layoutTraditional: "Traditional (Indented)",
    layoutPreview: "Layout Preview",
    minWords: "Min Words",
    maxWords: "Max Words",
    stop: "Stop",
    deleteChapter: "Delete Chapter",
    generateTitle: "Generate Title",
    worldBuilding: "World Building",
    charactersList: "Characters",
    storylinesList: "Storylines",
    storylines: "Storylines",
    worldSetting: "World Setting",
    targetChapters: "Target Chapters",
    batchProgress: "Batch Generation Progress",
    characterName: "Character Name",
    characterRole: "Role/Description",
    addCharacter: "Add Character",
    storylineTitle: "Storyline Title",
    storylineDesc: "Description",
    addStoryline: "Add Storyline",
    saveWorld: "Save World Building",
    refactor: "Structure with AI",
    refactoring: "Structuring...",
    basicSettings: "Basic Settings",
    novelDescription: "Novel Description",
    worldSettingPlaceholder: "### Geography\n- ...\n\n### Magic Systems\n- ...\n\n### History\n- ...",
    charactersPlaceholder: "List main characters and their traits...",
    storylinesPlaceholder: "Plan main plot points and subplots...",
    novelCover: "Novel Cover",
    uploadCover: "Upload Cover",
    coverUrlPlaceholder: "Enter cover image URL...",
    novelTitle: "Novel Title",
    aiSupplement: "AI Auto-supplement Settings",
    aiSupplementing: "Supplementing...",
    aiSupplementDesc: "AI will analyze existing chapters to automatically update characters, storylines, and world settings.",
    relationships: "Character Relationships",
    relationshipsPlaceholder: "Describe connections between characters...",
    edit: "Edit",
    batchGenerating: "Batch Generating...",
    currentChapters: "Current Chapters",
    totalWords: "Total Words",
    novelProgress: "Novel Progress",
    summarize: "Summarize",
    summary: "Summary",
    enforceWordCount: "Enforce Word Count Limit",
    autoSummarize: "Auto Summarize after Writing",
    outlineTitleUsed: "Using title from outline",
    fetchError: "Failed to fetch data from server",
    saveError: "Failed to save data to server",
    deleteError: "Failed to delete item",
    deleteSuccess: "Deleted successfully",
    createError: "Failed to create new item",
    deleteConfirm: "Are you sure you want to delete this version? This action cannot be undone.",
    noOutlineVersions: "No outline versions found. Create your first version to start planning.",
    scheduledTasks: "Scheduled Tasks",
    scheduleTask: "Schedule Task",
    taskType: "Task Type",
    generateChapter: "Generate Chapter",
    scheduleTime: "Schedule Time",
    taskStatus: "Status",
    pending: "Pending",
    running: "Running",
    completed: "Completed",
    failed: "Failed",
    taskCreated: "Task created successfully",
    taskDeleted: "Task deleted successfully",
    noTasks: "No scheduled tasks found.",
    addPrompt: "Add Template",
    setDefault: "Set as Default",
    selectNovel: "Select Novel",
    confirm: "Confirm",
    prompts: "Templates",
    promptsDesc: "Manage your AI generation templates.",
    logs: "Logs",
    logsDesc: "Recent system activities and operations.",
    aiConfig: "AI Config",
    aiConfigDesc: "Manage multiple AI provider configurations independently.",
    testConnection: "Test Connection",
    advancedParams: "Advanced Parameters",
    temperature: "Temperature",
    topP: "Top P",
    topK: "Top K",
    maxTokens: "Max Tokens",
    provider: "Provider",
    model: "Model",
    action: "Action",
    details: "Details",
    time: "Time",
    promptName: "Template Name",
    promptContent: "Template Content",
    promptType: "Template Type",
    confirmDeletePrompt: "Are you sure you want to delete this template?",
    deletePrompt: "Delete Template",
    promptDeleted: "Template deleted",
    isDefault: "Default",
    typeChapter: "Chapter Generation",
    typeOutline: "Outline Optimization",
    typeSummary: "Summary Generation",
    typeRefactor: "Content Refactor",
    typePolish: "Content Polishing",
    polish: "Polish",
    polishing: "Polishing...",
    recurrence: "Recurrence",
    recurrenceOnce: "Once",
    recurrenceDaily: "Daily",
  },
  zh: {
    confirmReset: "确定要重置所有设置吗？这将清除您的 AI 和写作配置。",
    resetSettings: "重置所有设置",
    previewOutline: "预览大纲",
    editOutline: "编辑大纲",
    appName: "墨流 (InkFlow)",
    prevPage: "上一页",
    nextPage: "下一页",
    page: "页",
    of: "共",
    total: "总计",
    dashboard: "控制面板",
    myNovels: "我的小说",
    statistics: "数据统计",
    settings: "设置",
    newNovel: "新建小说",
    welcomeBack: "欢迎回来，创作者",
    dashboardSub: "这是您今日的故事动态。",
    totalTokens: "总 Token 使用量",
    totalViews: "总浏览量",
    activeNovels: "活跃小说",
    tokenConsumption: "Token 消耗 (最近7天)",
    recentNovels: "最近小说",
    chapters: "章节",
    tokens: "Token",
    manageEmpire: "管理您的文学帝国。",
    progress: "进度",
    views: "浏览",
    editingChapter: "正在编辑章节",
    selectChapter: "请选择章节",
    save: "保存",
    addChapter: "添加章节",
    aiAssist: "AI 辅助",
    aiWriting: "AI 正在创作...",
    novelOutline: "小说大纲",
    outlinePlaceholder: "定义您的世界、角色和情节...",
    analytics: "数据分析",
    analyticsSub: "深入了解您的 Token 使用情况和表现。",
    tokenUsageByNovel: "各小说 Token 使用量",
    consumptionDistribution: "消耗分布",
    tokenHistoryLog: "Token 历史记录",
    novel: "小说",
    date: "日期",
    status: "状态",
    active: "活跃",
    enterTitle: "输入小说标题：",
    newNovelDraft: "新小说草稿",
    characters: "字符",
    words: "单词",
    autoSaved: "已自动保存",
    language: "语言",
    english: "英文",
    chinese: "中文简体",
    startWriting: "开始创作您的杰作...",
    selectToStart: "选择一个章节开始写作",
    fromLastWeek: "较上周",
    clear: "清除",
    outlineVersions: "大纲版本",
    activeVersion: "当前使用",
    newVersion: "新建版本",
    activate: "设为当前",
    versionName: "版本名称",
    outlineContext: "当前大纲上下文",
    deleteNovel: "删除小说",
    delete: "删除",
    confirmDelete: "您确定要删除这部小说吗？此操作无法撤销。",
    generateOutline: "AI 生成大纲",
    generatingOutline: "正在生成大纲...",
    batchGenerate: "一键生成章节",
    previewNovel: "预览小说",
    generateCount: "生成章节数量：",
    generatingChapters: "正在批量生成章节...",
    close: "关闭",
    cancel: "取消",
    novelStatus: "小说状态",
    novelDraft: "连载中",
    novelCompleted: "已完结",
    tableOfContents: "章节目录",
    aiSettings: "AI 设置",
    aiProvider: "AI 供应商",
    aiModel: "AI 模型",
    apiKey: "API 密钥",
    baseUrl: "基础 URL (可选)",
    saveSettings: "保存设置",
    settingsSaved: "设置已成功保存",
    gemini: "Google Gemini",
    openai: "OpenAI ChatGPT",
    deepseek: "DeepSeek",
    modelPlaceholder: "例如：gpt-4o, deepseek-chat",
    apiKeyPlaceholder: "输入您的 API 密钥",
    custom: "自定义 (兼容 OpenAI)",
    activeAI: "当前 AI",
    writingConfig: "创作配置",
    segmentedWrite: "分段创作",
    segmentedWriting: "正在分段创作...",
    wordCountRange: "字数范围",
    contentLayout: "内容排版",
    layoutStandard: "标准 (普通段落)",
    layoutWeb: "网文 (短段落/留白)",
    layoutTraditional: "传统 (首行缩进)",
    layoutPreview: "排版预览",
    minWords: "最小字数",
    maxWords: "最大字数",
    stop: "停止",
    deleteChapter: "删除章节",
    generateTitle: "生成标题",
    worldBuilding: "世界观/设定",
    charactersList: "角色列表",
    storylinesList: "故事线",
    storylines: "故事线",
    worldSetting: "世界设定",
    targetChapters: "目标章节数",
    batchProgress: "批量生成进度",
    characterName: "角色姓名",
    characterRole: "角色身份/描述",
    addCharacter: "添加角色",
    storylineTitle: "故事线标题",
    storylineDesc: "描述",
    addStoryline: "添加故事线",
    saveWorld: "保存设定",
    refactor: "AI 结构化",
    refactoring: "正在结构化...",
    basicSettings: "基础设置",
    novelDescription: "小说简介",
    worldSettingPlaceholder: "### 地理环境\n- ...\n\n### 力量体系\n- ...\n\n### 历史背景\n- ...",
    charactersPlaceholder: "列出主要角色及其特征...",
    storylinesPlaceholder: "规划主线剧情和支线...",
    novelCover: "小说封面",
    uploadCover: "上传封面",
    coverUrlPlaceholder: "输入封面图片 URL...",
    novelTitle: "小说名称",
    aiSupplement: "AI 自动补充设定",
    aiSupplementing: "正在补充...",
    aiSupplementDesc: "AI 将分析现有章节，自动更新角色、故事线和世界设定。",
    relationships: "人物关系线",
    relationshipsPlaceholder: "描述角色之间的联系（如：A 是 B 的导师，C 和 D 是死对头）...",
    edit: "编辑",
    batchGenerating: "批量生成中...",
    currentChapters: "当前章节",
    totalWords: "总字数",
    novelProgress: "创作进度",
    summarize: "生成摘要",
    summary: "摘要",
    enforceWordCount: "启用字数限制",
    autoSummarize: "写完后自动生成摘要",
    outlineTitleUsed: "采用大纲标题",
    fetchError: "从服务器获取数据失败",
    saveError: "保存数据到服务器失败",
    deleteError: "删除失败",
    deleteSuccess: "删除成功",
    createError: "创建失败",
    deleteConfirm: "您确定要删除这个版本吗？此操作无法撤销。",
    noOutlineVersions: "暂无大纲版本。请创建您的第一个版本开始规划。",
    scheduledTasks: "定时任务",
    scheduleTask: "创建任务",
    taskType: "任务类型",
    generateChapter: "自动生成章节",
    scheduleTime: "执行时间",
    taskStatus: "状态",
    pending: "等待中",
    running: "执行中",
    completed: "已完成",
    failed: "失败",
    taskCreated: "任务创建成功",
    taskDeleted: "任务删除成功",
    noTasks: "暂无定时任务。",
    addPrompt: "添加模板",
    setDefault: "设为默认",
    selectNovel: "选择小说",
    confirm: "确认",
    prompts: "提示词模板",
    promptsDesc: "管理您的 AI 生成提示词模板。",
    logs: "操作日志",
    logsDesc: "最近的系统活动和操作记录。",
    aiConfig: "模型配置",
    aiConfigDesc: "独立管理多个 AI 供应商配置。",
    testConnection: "测试连接",
    advancedParams: "高级参数",
    temperature: "温度 (Temperature)",
    topP: "Top P",
    topK: "Top K",
    maxTokens: "最大 Token",
    provider: "供应商",
    model: "模型",
    action: "操作",
    details: "详情",
    time: "时间",
    promptName: "模板名称",
    promptContent: "模板内容",
    promptType: "模板类型",
    confirmDeletePrompt: "确定要删除这个模板吗？",
    deletePrompt: "删除模板",
    promptDeleted: "模板已删除",
    isDefault: "默认",
    typeChapter: "章节生成",
    typeOutline: "大纲优化",
    typeSummary: "摘要生成",
    typeRefactor: "内容重构",
    typePolish: "内容润色",
    polish: "内容润色",
    polishing: "正在润色...",
    recurrence: "重复周期",
    recurrenceOnce: "仅一次",
    recurrenceDaily: "每天",
  }
};

export type Language = 'en' | 'zh';
