export const translations = {
  en: {
    confirmReset: "Are you sure you want to reset all settings? This will clear your AI and writing configurations.",
    resetSettings: "Reset All Settings",
    previewOutline: "Preview Outline",
    editOutline: "Edit Outline",
    appName: "InkFlow",
    prevPage: "Previous",
    nextPage: "Next",
    page: "Page",
    of: "of",
    total: "Total",
    dashboard: "Dashboard",
    myNovels: "My Novels",
    statistics: "Statistics",
    settings: "Settings",
    newNovel: "New Novel",
    welcomeBack: "Welcome back, Creator",
    dashboardSub: "Here's what's happening with your stories today.",
    totalTokens: "Total Tokens Used",
    totalViews: "Total Views",
    activeNovels: "Active Novels",
    tokenConsumption: "Token Consumption (Last 7 Days)",
    recentNovels: "Recent Novels",
    chapters: "Chapters",
    tokens: "Tokens",
    manageEmpire: "Manage your literary empire.",
    progress: "Progress",
    views: "Views",
    editingChapter: "Editing Chapter",
    selectChapter: "Select a chapter",
    save: "Save",
    addChapter: "Add Chapter",
    aiAssist: "AI Assist",
    aiWriting: "AI is writing...",
    novelOutline: "Novel Outline",
    outlinePlaceholder: "Define your world, characters, and plot...",
    analytics: "Analytics",
    analyticsSub: "Deep dive into your token usage and performance.",
    tokenUsageByNovel: "Token Usage by Novel",
    consumptionDistribution: "Consumption Distribution",
    tokenHistoryLog: "Token History Log",
    novel: "Novel",
    date: "Date",
    status: "Status",
    active: "Active",
    enterTitle: "Enter novel title:",
    newNovelDraft: "New novel draft",
    characters: "characters",
    words: "words",
    autoSaved: "Auto-saved",
    language: "Language",
    english: "English",
    chinese: "Chinese (Simplified)",
    startWriting: "Start writing your masterpiece...",
    selectToStart: "Select a chapter to start writing",
    fromLastWeek: "from last week",
    clear: "Clear",
    outlineVersions: "Outline Versions",
    activeVersion: "Active",
    newVersion: "New Version",
    activate: "Activate",
    versionName: "Version Name",
    outlineContext: "Active Outline Context",
    deleteNovel: "Delete Novel",
    delete: "Delete",
    confirmDelete: "Are you sure you want to delete this novel? This action cannot be undone.",
    generateOutline: "AI Generate Outline",
    generatingOutline: "Generating Outline...",
    batchGenerate: "Batch Generate",
    previewNovel: "Preview Novel",
    generateCount: "Number of chapters:",
    generatingChapters: "Generating chapters...",
    close: "Close",
    cancel: "Cancel",
    novelStatus: "Novel Status",
    novelDraft: "In Progress",
    novelCompleted: "Completed",
    tableOfContents: "Table of Contents",
    aiSettings: "AI Settings",
    aiProvider: "AI Provider",
    aiModel: "AI Model",
    apiKey: "API Key",
    baseUrl: "Base URL (Optional)",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved successfully",
    gemini: "Google Gemini",
    openai: "OpenAI ChatGPT",
    deepseek: "DeepSeek",
    modelPlaceholder: "e.g., gpt-4o, deepseek-chat",
    apiKeyPlaceholder: "Enter your API key",
    custom: "Custom (OpenAI Compatible)",
    activeAI: "Active AI",
    writingConfig: "Writing Configuration",
    segmentedWrite: "Segmented Write",
    segmentedWriting: "Writing Segment...",
    wordCountRange: "Word Count Range",
    contentLayout: "Content Layout",
    layoutStandard: "Standard (Paragraphs)",
    layoutWeb: "Web Novel (Short Paragraphs)",
    layoutTraditional: "Traditional (Indented)",
    layoutPreview: "Layout Preview",
    minWords: "Min Words",
    maxWords: "Max Words",
    stop: "Stop",
    deleteChapter: "Delete Chapter",
    generateTitle: "Generate Title",
    worldBuilding: "World Building",
    charactersList: "Characters",
    storylinesList: "Storylines",
    storylines: "Storylines",
    worldSetting: "World Setting",
    targetChapters: "Target Chapters",
    batchProgress: "Batch Generation Progress",
    characterName: "Character Name",
    characterRole: "Role/Description",
    addCharacter: "Add Character",
    storylineTitle: "Storyline Title",
    storylineDesc: "Description",
    addStoryline: "Add Storyline",
    saveWorld: "Save World Building",
    refactor: "Structure with AI",
    refactoring: "Structuring...",
    basicSettings: "Basic Settings",
    novelDescription: "Novel Description",
    worldSettingPlaceholder: "### Geography\n- ...\n\n### Magic Systems\n- ...\n\n### History\n- ...",
    charactersPlaceholder: "List main characters and their traits...",
    storylinesPlaceholder: "Plan main plot points and subplots...",
    novelCover: "Novel Cover",
    uploadCover: "Upload Cover",
    coverUrlPlaceholder: "Enter cover image URL...",
    novelTitle: "Novel Title",
    aiSupplement: "AI Auto-supplement Settings",
    aiSupplementing: "Supplementing...",
    aiSupplementDesc: "AI will analyze existing chapters to automatically update characters, storylines, and world settings.",
    lastSupplementAt: "Last Supplemented",
    relationships: "Character Relationships",
    relationshipsPlaceholder: "Describe connections between characters...",
    preview: "Preview",
    edit: "Edit",
    batchGenerating: "Batch Generating...",
    currentChapters: "Current Chapters",
    totalWords: "Total Words",
    novelProgress: "Novel Progress",
    summarize: "Summarize",
    summary: "Summary",
    enforceWordCount: "Enforce Word Count Limit",
    autoSummarize: "Auto Summarize after Writing",
    outlineTitleUsed: "Using title from outline",
    fetchError: "Failed to fetch data from server",
    export: "Export",
    exportMarkdown: "Export Markdown",
    exportEpub: "Export EPUB",
    exporting: "Exporting...",
    exportSuccess: "Export successful",
    exportError: "Export failed",
    saveError: "Failed to save data to server",
    deleteError: "Failed to delete item",
    deleteSuccess: "Deleted successfully",
    createError: "Failed to create new item",
    aiError: "AI operation failed",
    deleteConfirm: "Are you sure you want to delete this version? This action cannot be undone.",
    noOutlineVersions: "No outline versions found. Create your first version to start planning.",
    scheduledTasks: "Scheduled Tasks",
    scheduleTask: "Schedule Task",
    taskType: "Task Type",
    generateChapter: "Generate Chapter",
    scheduleTime: "Schedule Time",
    taskStatus: "Status",
    pending: "Pending",
    running: "Running",
    completed: "Completed",
    failed: "Failed",
    taskCreated: "Task created successfully",
    taskDeleted: "Task deleted successfully",
    noTasks: "No scheduled tasks found.",
    addPrompt: "Add Template",
    setAsDefault: "Set as Default",
    selectNovel: "Select Novel",
    confirm: "Confirm",
    prompts: "Templates",
    promptsDesc: "Manage your AI generation templates.",
    logs: "Logs",
    logsDesc: "Recent system activities and operations.",
    aiConfig: "AI Config",
    aiConfigDesc: "Manage multiple AI provider configurations independently.",
    testConnection: "Test Connection",
    advancedParams: "Advanced Parameters",
    temperature: "Temperature",
    topP: "Top P",
    topK: "Top K",
    maxTokens: "Max Tokens",
    provider: "Provider",
    model: "Model",
    action: "Action",
    details: "Details",
    time: "Time",
    promptName: "Template Name",
    promptContent: "Template Content",
    promptType: "Template Type",
    confirmDeletePrompt: "Are you sure you want to delete this template?",
    deletePrompt: "Delete Template",
    promptDeleted: "Template deleted",
    isDefault: "Default",
    typeChapter: "Chapter Generation",
    typeOutline: "Outline Optimization",
    typeSummary: "Summary Generation",
    typeRefactor: "Content Refactor",
    typePolish: "Content Polishing",
    typeDescription: "Novel Description",
    polish: "Polish",
    polishing: "Polishing...",
    recurrence: "Recurrence",
    recurrenceOnce: "Once",
    recurrenceDaily: "Daily",
    promptCreated: "Template created",
    promptUpdated: "Template updated",
    promptSaveError: "Failed to save template",
    promptSetDefault: "Set as default template",
    taskStarted: "Task started",
    novelTitleLabel: "Novel Title",
    novelGenreLabel: "Genre/Style",
    novelGenrePlaceholder: "e.g., Fantasy, Urban, Sci-Fi...",
    confirmDeleteTitle: "Confirm Delete",
    confirmResetTitle: "Confirm Reset",
    startGenerating: "Start Generating",
    chapterPrefix: "Chapter ",
    chapterSuffix: "",
    noContent: "(No content)",
    aiThinking: "AI is thinking of a great plot, please wait...",
    saving: "Saving...",
    targetChaptersDesc: "Setting a target chapter count helps AI control the story pace and automatically conclude as it nears the end.",
    novelDescPlaceholder: "Briefly describe the theme, core conflict, and target audience...",
    worldSettingDesc: "Define geography, magic systems, history, social rules, etc. AI will refer to these to ensure consistency.",
    charactersDesc: "List main characters, traits, appearance, and motivations.",
    storylinesDesc: "Plan main plot points, subplots, foreshadowing, and climaxes.",
    relationshipsDesc: "Visualize complex connections and emotional bonds between characters.",
    visualOverview: "Visual Overview",
    storyProgression: "Story Progression",
    beginning: "Beginning",
    development: "Development",
    climax: "Climax",
    ending: "Ending",
    type: "Type",
    simulatePublish: "Simulate Publish",
    runNow: "Run Now",
    all: "All",
    noTemplates: "No templates found",
    addFirstPrompt: "Click the button in the top right to add your first template",
    editPrompt: "Edit Template",
    promptNamePlaceholder: "e.g., Fantasy Style Chapter Generation",
    promptContentPlaceholder: "Enter template content...",
    aiGenerating: "AI Generating",
    generateTitleLabel: "Generate Title",
    generateDescriptionLabel: "Generate Description",
    finalChapterPrompt: "Write the final chapter of the novel ({title}). Bring a satisfying conclusion to the story and resolve all major plot points.",
    descriptionPrompt: "Based on the following novel outline, write a compelling novel description (summary). The description should be between 80 and 150 words, highlighting the core conflict, main characters, and unique selling points of the story.\n\nOutline:\n{outline}",
    nextChapterPrompt: "Write Chapter {num} ({title}). Focus on advancing the plot according to the outline. Current progress: {num}/{total} chapters.",
    refactorPrompt: "Please refactor and polish the following novel chapter content:",
    novelTitleContext: "Novel Title",
    outlineContextLabel: "Outline",
    layoutStrictContext: "Important: Please strictly follow the {layout} layout style.",
    continueWritingPrompt: "Continue writing Chapter \"{title}\". Current content is:",
    segmentedWritePrompt: "Strict layout: Use {layout} style. For web novels, this means a maximum of 2 sentences per paragraph.",
    segmentedPartPrompt: "This is part {current} of Chapter \"{title}\" (total {total} parts).",
    segmentedContinuePrompt: "Continue writing from where the previous part ended. Do not repeat previous sentences. Start the next action or dialogue immediately.",
    segmentedStartPrompt: "Start writing this chapter from the beginning.",
    contextBackground: "Previous Background",
    descriptionContextLabel: "Description",
    targetChaptersContextLabel: "Target Chapters",
    charactersContextLabel: "Characters",
    worldSettingContextLabel: "World Setting",
    undefinedContext: "Undefined",
    genericError: "An error occurred",
    saveSuccess: "Saved successfully",
    targetReached: "Target reached",
    mockPublish: "Mock Publish",
    noLogs: "No history logs found.",
    tasksDesc: "Manage your automated generation tasks.",
    layoutStandardDesc: "Balanced paragraphs for a smooth reading experience.",
    layoutWebDesc: "Optimized for mobile with frequent breaks and high readability.",
    layoutTraditionalDesc: "Classic literary style with indented first lines and dense text.",
    style: "STYLE",
    previewMode: "PREVIEW MODE",
    versionNamePlaceholder: "e.g. V2.0",
    chooseCoverFile: "Choose cover file",
    customCountPlaceholder: "Custom count...",
    maxLabel: "Max",
    emptySummaryError: "AI returned an empty summary. Please try again.",
    aiGenerated: "AI Generated",
    generatingTitle: "Generating chapter title from outline...",
    aiSummarizing: "AI is summarizing...",
    system: "System",
    library: "Library",
    threads: "Threads",
    network: "Network",
    unknown: "Unknown",
    failedToSaveSettings: "Failed to save settings",
    supports: "Supports",
    layoutPreviewP1: "The sun dipped below the horizon, painting the sky in hues of violet and gold.",
    layoutPreviewP1Long: "The sun dipped below the horizon, painting the sky in hues of violet and gold. A cool breeze swept through the valley, carrying the scent of pine and damp earth.",
    layoutPreviewP2: "Kael stood at the edge of the cliff, his cloak billowing behind him.",
    layoutPreviewP2Long: "Kael stood at the edge of the cliff, his cloak billowing behind him like a dark wing. He had waited for this moment for years, ever since the day the elders had spoken of the prophecy.",
    layoutPreviewP3: '"It\'s time," he whispered to the wind.',
    layoutPreviewP4: "The journey ahead would be long and treacherous.",
    layoutPreviewP4Long: "The journey ahead would be long and treacherous, but he was ready. With one last look at his home, he stepped forward into the unknown.",
  },
  zh: {
    confirmReset: "确定要重置所有设置吗？这将清除您的 AI 和写作配置。",
    resetSettings: "重置所有设置",
    previewOutline: "预览大纲",
    editOutline: "编辑大纲",
    appName: "墨流 (InkFlow)",
    prevPage: "上一页",
    nextPage: "下一页",
    page: "页",
    of: "共",
    total: "总计",
    dashboard: "控制面板",
    myNovels: "我的小说",
    statistics: "数据统计",
    settings: "设置",
    newNovel: "新建小说",
    welcomeBack: "欢迎回来，创作者",
    dashboardSub: "这是您今日的故事动态。",
    totalTokens: "总 Token 使用量",
    totalViews: "总浏览量",
    activeNovels: "活跃小说",
    tokenConsumption: "Token 消耗 (最近7天)",
    recentNovels: "最近小说",
    chapters: "章节",
    tokens: "Token",
    manageEmpire: "管理您的文学帝国。",
    progress: "进度",
    views: "浏览",
    editingChapter: "正在编辑章节",
    selectChapter: "请选择章节",
    save: "保存",
    addChapter: "添加章节",
    aiAssist: "AI 辅助",
    aiWriting: "AI 正在创作...",
    novelOutline: "小说大纲",
    outlinePlaceholder: "定义您的世界、角色和情节...",
    analytics: "数据分析",
    analyticsSub: "深入了解您的 Token 使用情况和表现。",
    tokenUsageByNovel: "各小说 Token 使用量",
    consumptionDistribution: "消耗分布",
    tokenHistoryLog: "Token 历史记录",
    novel: "小说",
    date: "日期",
    status: "状态",
    active: "活跃",
    enterTitle: "输入小说标题：",
    newNovelDraft: "新小说草稿",
    characters: "字符",
    words: "单词",
    autoSaved: "已自动保存",
    language: "语言",
    english: "英文",
    chinese: "中文简体",
    startWriting: "开始创作您的杰作...",
    selectToStart: "选择一个章节开始写作",
    fromLastWeek: "较上周",
    clear: "清除",
    outlineVersions: "大纲版本",
    activeVersion: "当前使用",
    newVersion: "新建版本",
    activate: "设为当前",
    versionName: "版本名称",
    outlineContext: "当前大纲上下文",
    deleteNovel: "删除小说",
    delete: "删除",
    confirmDelete: "您确定要删除这部小说吗？此操作无法撤销。",
    generateOutline: "AI 生成大纲",
    generatingOutline: "正在生成大纲...",
    batchGenerate: "一键生成章节",
    previewNovel: "预览小说",
    generateCount: "生成章节数量：",
    generatingChapters: "正在批量生成章节...",
    close: "关闭",
    cancel: "取消",
    novelStatus: "小说状态",
    novelDraft: "连载中",
    novelCompleted: "已完结",
    tableOfContents: "章节目录",
    aiSettings: "AI 设置",
    aiProvider: "AI 供应商",
    aiModel: "AI 模型",
    apiKey: "API 密钥",
    baseUrl: "基础 URL (可选)",
    saveSettings: "保存设置",
    settingsSaved: "设置已成功保存",
    gemini: "Google Gemini",
    openai: "OpenAI ChatGPT",
    deepseek: "DeepSeek",
    modelPlaceholder: "例如：gpt-4o, deepseek-chat",
    apiKeyPlaceholder: "输入您的 API 密钥",
    custom: "自定义 (兼容 OpenAI)",
    activeAI: "当前 AI",
    writingConfig: "创作配置",
    segmentedWrite: "分段创作",
    segmentedWriting: "正在分段创作...",
    wordCountRange: "字数范围",
    contentLayout: "内容排版",
    layoutStandard: "标准 (普通段落)",
    layoutWeb: "网文 (短段落/留白)",
    layoutTraditional: "传统 (首行缩进)",
    layoutPreview: "排版预览",
    minWords: "最小字数",
    maxWords: "最大字数",
    stop: "停止",
    deleteChapter: "删除章节",
    generateTitle: "生成标题",
    worldBuilding: "世界观/设定",
    charactersList: "角色列表",
    storylinesList: "故事线",
    storylines: "故事线",
    worldSetting: "世界设定",
    targetChapters: "目标章节数",
    batchProgress: "批量生成进度",
    characterName: "角色姓名",
    characterRole: "角色身份/描述",
    addCharacter: "添加角色",
    storylineTitle: "故事线标题",
    storylineDesc: "描述",
    addStoryline: "添加故事线",
    saveWorld: "保存设定",
    refactor: "AI 结构化",
    refactoring: "正在结构化...",
    basicSettings: "基础设置",
    novelDescription: "小说简介",
    worldSettingPlaceholder: "### 地理环境\n- ...\n\n### 力量体系\n- ...\n\n### 历史背景\n- ...",
    charactersPlaceholder: "列出主要角色及其特征...",
    storylinesPlaceholder: "规划主线剧情和支线...",
    novelCover: "小说封面",
    uploadCover: "上传封面",
    coverUrlPlaceholder: "输入封面图片 URL...",
    novelTitle: "小说名称",
    aiSupplement: "AI 自动补充设定",
    aiSupplementing: "正在补充...",
    aiSupplementDesc: "AI 将分析现有章节，自动更新角色、故事线和世界设定。",
    lastSupplementAt: "最近补充时间",
    relationships: "人物关系线",
    relationshipsPlaceholder: "描述角色之间的联系（如：A 是 B 的导师，C 和 D 是死对头）...",
    preview: "预览",
    edit: "编辑",
    batchGenerating: "批量生成中...",
    currentChapters: "当前章节",
    totalWords: "总字数",
    novelProgress: "创作进度",
    summarize: "生成摘要",
    summary: "摘要",
    enforceWordCount: "启用字数限制",
    autoSummarize: "写完后自动生成摘要",
    outlineTitleUsed: "采用大纲标题",
    fetchError: "从服务器获取数据失败",
    saveError: "保存数据到服务器失败",
    deleteError: "删除失败",
    deleteSuccess: "删除成功",
    createError: "创建失败",
    deleteConfirm: "您确定要删除这个版本吗？此操作无法撤销。",
    noOutlineVersions: "暂无大纲版本。请创建您的第一个版本开始规划。",
    scheduledTasks: "定时任务",
    scheduleTask: "创建任务",
    taskType: "任务类型",
    generateChapter: "自动生成章节",
    scheduleTime: "执行时间",
    taskStatus: "状态",
    pending: "等待中",
    running: "执行中",
    completed: "已完成",
    failed: "失败",
    taskCreated: "任务创建成功",
    taskDeleted: "任务删除成功",
    noTasks: "暂无定时任务。",
    addPrompt: "添加模板",
    setAsDefault: "设为默认",
    selectNovel: "选择小说",
    confirm: "确认",
    prompts: "提示词模板",
    promptsDesc: "管理您的 AI 生成提示词模板。",
    logs: "操作日志",
    logsDesc: "最近的系统活动和操作记录。",
    aiConfig: "模型配置",
    aiConfigDesc: "独立管理多个 AI 供应商配置。",
    testConnection: "测试连接",
    advancedParams: "高级参数",
    temperature: "温度 (Temperature)",
    topP: "Top P",
    topK: "Top K",
    maxTokens: "最大 Token",
    provider: "供应商",
    model: "模型",
    action: "操作",
    details: "详情",
    time: "时间",
    promptName: "模板名称",
    promptContent: "模板内容",
    promptType: "模板类型",
    confirmDeletePrompt: "确定要删除这个模板吗？",
    deletePrompt: "删除模板",
    promptDeleted: "模板已删除",
    isDefault: "默认",
    typeChapter: "章节生成",
    typeOutline: "大纲优化",
    typeSummary: "摘要生成",
    typeRefactor: "内容重构",
    typePolish: "内容润色",
    typeDescription: "简介生成",
    polish: "内容润色",
    polishing: "正在润色...",
    recurrence: "重复周期",
    recurrenceOnce: "仅一次",
    recurrenceDaily: "每天",
    promptCreated: "提示词已创建",
    promptUpdated: "提示词已更新",
    promptSaveError: "保存提示词失败",
    promptSetDefault: "已设为默认提示词",
    taskStarted: "任务已开始执行",
    novelTitleLabel: "小说标题",
    novelGenreLabel: "类型/风格",
    novelGenrePlaceholder: "例如：玄幻、都市、科幻...",
    confirmDeleteTitle: "确认删除",
    confirmResetTitle: "确认重置",
    startGenerating: "开始生成",
    chapterPrefix: "第",
    chapterSuffix: "章",
    noContent: "（暂无内容）",
    aiThinking: "AI 正在为您构思精彩剧情，请稍候...",
    saving: "保存中...",
    targetChaptersDesc: "设置目标章节数可以帮助 AI 更好地控制故事节奏并在接近尾声时自动完结。",
    novelDescPlaceholder: "简述小说的主题、核心冲突和目标读者...",
    worldSettingDesc: "定义地理环境、力量体系、历史背景、社会规则等。AI 将参考这些设定来保证世界观的一致性。",
    charactersDesc: "列出主要角色、性格特征、外貌描写及核心动机。",
    storylinesDesc: "规划主线剧情、支线任务、伏笔和高潮点。",
    relationshipsDesc: "可视化展示角色之间的复杂联系与情感纽带。",
    visualOverview: "可视化概览",
    storyProgression: "故事进展曲线",
    beginning: "开端",
    development: "发展",
    climax: "高潮",
    ending: "结局",
    type: "类型",
    simulatePublish: "模拟发布",
    runNow: "立即执行",
    all: "全部",
    noTemplates: "暂无模板",
    addFirstPrompt: "点击右上角按钮添加您的第一个提示词模板",
    editPrompt: "编辑提示词",
    promptNamePlaceholder: "例如：玄幻风格章节生成",
    promptContentPlaceholder: "输入提示词内容...",
    aiGenerating: "AI 生成",
    generateTitleLabel: "生成标题",
    generateDescriptionLabel: "生成简介",
    finalChapterPrompt: "创作小说的最终章（{title}）。为故事带来圆满的结局，并解决所有主要情节。",
    descriptionPrompt: "根据以下小说大纲，撰写一段引人入胜的小说简介。简介字数控制在 80 到 150 字之间，突出核心冲突、主要人物以及故事的独特卖点。\n\n大纲：\n{outline}",
    nextChapterPrompt: "创作第 {num} 章（{title}）。重点是根据大纲推进情节。当前进度：{num}/{total} 章。",
    refactorPrompt: "请对以下小说章节内容进行重构和润色：",
    novelTitleContext: "小说标题",
    outlineContextLabel: "大纲",
    layoutStrictContext: "重要：请严格遵守 {layout} 排版风格。",
    continueWritingPrompt: "继续创作章节《{title}》。当前内容为：",
    segmentedWritePrompt: "严格排版：使用 {layout} 风格。对于网络小说，这意味着每段最多 2 句话。",
    segmentedPartPrompt: "这是章节《{title}》的第 {current} 段（共 {total} 段）。",
    segmentedContinuePrompt: "从上文结束的地方继续创作。不要重复之前的句子。立即开始接下来的行动或对话。",
    segmentedStartPrompt: "从头开始创作本章。",
    contextBackground: "上文背景",
    descriptionContextLabel: "描述",
    targetChaptersContextLabel: "目标总章节",
    charactersContextLabel: "角色",
    worldSettingContextLabel: "世界设定",
    undefinedContext: "未定义",
    genericError: "发生错误",
    saveSuccess: "保存成功",
    aiError: "AI 操作失败",
    targetReached: "已达到目标",
    inProgress: "连载中",
    completedNovel: "已完结",
    wordCount: "字数",
    export: "导出",
    exportMarkdown: "导出 Markdown",
    exportEpub: "导出 EPUB",
    exporting: "正在导出...",
    exportSuccess: "导出成功",
    exportError: "导出失败",
    mockPublish: "模拟发布",
    noLogs: "暂无历史记录",
    tasksDesc: "管理您的自动化生成任务。",
    layoutStandardDesc: "均衡的段落结构，提供流畅的阅读体验。",
    layoutWebDesc: "针对移动端优化，段落简短，易于快速阅读。",
    layoutTraditionalDesc: "经典文学风格，首行缩进，文本密度较高。",
    style: "排版风格",
    previewMode: "预览模式",
    versionNamePlaceholder: "例如：第二版",
    chooseCoverFile: "选择封面文件",
    customCountPlaceholder: "自定义数量...",
    maxLabel: "最大",
    emptySummaryError: "AI 返回了空摘要。请重试。",
    aiGenerated: "AI 生成",
    generatingTitle: "正在从大纲生成章节标题...",
    aiSummarizing: "AI 正在生成摘要...",
    system: "系统",
    library: "库",
    threads: "线索",
    network: "网络",
    unknown: "未知",
    failedToSaveSettings: "保存设置失败",
    supports: "支持",
    layoutPreviewP1: "夕阳沉入地平线，将天空染成紫罗兰色和金色。",
    layoutPreviewP1Long: "夕阳沉入地平线，将天空染成紫罗兰色和金色。一阵凉爽的微风席卷山谷，带着松树和潮湿泥土的香气。",
    layoutPreviewP2: "凯尔站在悬崖边，斗篷在身后飘扬。",
    layoutPreviewP2Long: "凯尔站在悬崖边，斗篷在身后飘扬，如同一只黑暗的翅膀。他等待这一刻已经很多年了，自从长老们谈论那个预言的那天起。",
    layoutPreviewP3: "“是时候了，”他对着风低声说道。",
    layoutPreviewP4: "前方的旅程将漫长而艰险。",
    layoutPreviewP4Long: "前方的旅程将漫长而艰险，但他已经准备好了。最后看了一眼家乡，他迈步走向未知。",
  }
};

export type Language = 'en' | 'zh';
